name: Push Events
on: 
  schedule:
    - cron: '*/5 * * * *'   #run every 5 minutes
jobs:
  show-info:
      runs-on: ubuntu-latest
      steps:
      - name: info
        run: |
          echo "this is push event on all the branches"
        
          
  
