name: Push Events
on: 
  push:
    branches:
      - main
      - test
      - test2
jobs:
  show-info:
      runs-on: ubuntu-latest
      steps:
      - name: info
        run: |
          echo "this is push event on all the branches"
        
          
  
