name: Manual workflow
on: 
  issues:
    types:
      - opened
jobs:
  run-manual-tasks:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: info
        run: |
          echo "running manual tasks"
        
          
  
